### ISSUE TITLE
readme 파일을 추가해주세요

### ISSUE THREAD

**Issue by KimChanHyo** [shekwl24/maplecal#1]
readme 파일에 프로젝트에 대한 간단한 설명, 사용 법(최소한 링크라도) 등의 내용을 추가해주면 좋겠네요

**Comment by shekwl24** [comment]
센세 감동ㅜㅜ
 
readme는 추가할게여 ㄳㄳ
 
maplecal.com 
지금 요기 주소는 서버 과부하 걸려서 검색 기능 막아놨는데
 
maplecal.com:90
여기 포트는 검색기능 구현해놨어요 이용해봐여 
 
2시간 뒤 30분 뒤 출근 ㅎㅇㅌ

**Comment by shekwl24** [comment]
추가했습니다. 감사합니다.
