### ISSUE TITLE
Symbol 계산기 자동 검색기능 오류

### ISSUE THREAD

**Issue by integerblue** [shekwl24/maplecal#3]
캐릭터 정보 공개에 동의했음에도 불구하고 비공개 상태라고 불러오지 못하는 현상이 일어납니다.

**Comment by shekwl24** [comment]
네. 간헐적으로 오류가 발생하여 서버측 문제로 예상하고 있습니다. heroku가 해외 호스팅업체라 국내 호스팅 업체로 이전 계획 중에 있습니다. 불편하시더라도 닉네임 입력 후 검색을 2~3회 시도 하시면 사용은 가능합니다. 의견 감사드립니다.

**Comment by integerblue** [comment]
간헐적으로 작동하지 않는 것이 아니라 모든 캐릭터에 대해 항상 작동하지 않습니다.
캐릭터 정보 비공개 상태라는 오류가 발생합니다.
다시 한 번 확인 부탁드립니다.

**Comment by shekwl24** [comment]
현재 모바일 기기를 이용하여 다른 네트워크에서도 작동을 확인해보았는데 정상적으로 작동합니다. 혹시 닉네임 알려주시면 테스트 해보겠습니다

**Comment by integerblue** [comment]
'정뚜모범생' 체크 부탁드립니다!

**Comment by shekwl24** [comment]
아아 확인해보니 리부트와 일반월드가 구분되어 있네요. 현재 제 사이트는 현재 일반 월드에 한해서만 검색이 가능합니다. 리부트도 검색가능토록 기능업데이트 하겠습니다. 덕분에 발견했네요 감사합니다

**Comment by shekwl24** [comment]
리부트 업데이트 진행했습니다. 확인 되시면 코멘트부탁드릴게여

**Comment by integerblue** [comment]
앗 잘 작동합니다! 감사합니다!

**Comment by integerblue** [comment]
같은 이슈가 다시 발생하고 있습니다. 확인 부탁드립니다.

**Comment by shekwl24** [comment]
안되시는 닉네임 알려주시면 감사하겠습니다.  '정뚜모범생'은 잘 검색되네요

**Comment by integerblue** [comment]
아 이게 간헐적으로 안될 때가 있네요
감사합니다.
